name: test-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write

    steps:
      - run: make test